apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data
resources:
  - statefulset.yaml
  - service.yaml
  - init-sql-configmap.yaml
  - exporter.yaml
  - exporter-queries-configmap.yaml
  - exporter-servicemonitor.yaml
