spark_job:
  repository: ghcr.io/ferguske/trend-intelligence-platform/spark-jobs
  tag: sha-0000000   # spark-ci bump
dbt:
  repository: ghcr.io/ferguske/trend-intelligence-platform/dbt
  tag: sha-0000000   # dbt-ci bump
